---

variables:
  MAJOR: 4
  TMP_IMAGE: $CI_REGISTRY_IMAGE/tmp/$SCANNER:$CI_COMMIT_SHA
  SCANNER: trivy

include:
#   - template: Security/Dependency-Scanning.gitlab-ci.yml
#   - template: Security/License-Scanning.gitlab-ci.yml
  - local: .gitlab/maintenance.yml

# # Workaround to the detached pipeline as described in
# # https://gitlab.com/gitlab-org/gitlab/-/issues/34756
# workflow:
#   rules:
#     - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "detached"'
#       when: never
#     - when: always

stages:
  - maintenance

.not-on-schedule:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_PIPELINE_SOURCE != "schedule"'
      when: on_success

.ruby-alpine:
  extends: .not-on-schedule
  image: ruby:2.7.2-alpine
  before_script:
    - apk add git
    - bundle config --local jobs "$(nproc)"
    - bundle config set no-cache 'true'
    - bundle install --quiet

