---
inherit_gem:
  gitlab-styles:
    - rubocop-default.yml

Rails:
  Enabled: false

CodeReuse/ActiveRecord:
  Enabled: false

AllCops:
  Exclude:
    - 'Rakefile'
    - 'bin/*'

RSpec/MultipleMemoizedHelpers:
  Max: 10
