---
inherit_gem:
  gitlab-styles:
    - rubocop-default.yml

CodeReuse/ActiveRecord:
  Enabled: false

Rails/Exit:
  Enabled: false

AllCops:
  Exclude:
    - 'Rakefile'
    - 'bin/*'
    - 'vendor/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 10