#!/bin/sh

set -e

cd "$(dirname "$0")/.."
pwd

if command -v apt-get; then
  apt-get clean
  apt-get update -q
  apt-get install -y --no-install-recommends \
    curl \
    gnupg2
fi

if [ ! -f /usr/sbin/haproxy ] && command -v apt-get; then
  echo deb http://deb.debian.org/debian buster-backports main  > /etc/apt/sources.list.d/backports.list
  apt-get update -y && apt-get install -y --no-install-recommends build-essential haproxy=2.2.\*
fi
