#!/usr/bin/env ruby
# frozen_string_literal: true

require 'gcs'

Signal.trap('INT') do
  exit(1)
end

begin
  # load a custom .bashrc script to inflate all database files before executing
  # any scanner commands.
  `/bin/bash $HOME/.bashrc`
  Gcs::Cli.start(ARGV)
rescue StandardError => e
  Gcs.logger.error(e.message)
  Gcs.logger.error(e.backtrace.join("\n")) if Gcs::Environment.debug?
  exit 1
end
